language: python

python:
  - 3.6

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install numpydoc

script:
  # Use Sphinx to make the html docs
  - cd docs
  - make html
  - touch docs/_build/html/.nojekyll
    
# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs/_build/html/
  target-branch: gh-pages # This is the default branch but I add it here anyway
  on:
    branch: master
